const teams = [
	{ code: "ARI", fullName: "Arizona Cardinals", shortName: "Arizona" },
	{ code: "ATL", fullName: "Atlanta Falcons", shortName: "Atlanta" },
	{ code: "BAL", fullName: "Baltimore Ravens", shortName: "Baltimore" },
	{ code: "BUF", fullName: "Buffalo Bills", shortName: "Buffalo" },
	{ code: "CAR", fullName: "Carolina Panthers", shortName: "Carolina" },
	{ code: "CHI", fullName: "Chicago Bears", shortName: "Chicago" },
	{ code: "CIN", fullName: "Cincinnati Bengals", shortName: "Cincinnati" },
	{ code: "CLE", fullName: "Cleveland Browns", shortName: "Cleveland" },
	{ code: "DAL", fullName: "Dallas Cowboys", shortName: "Dallas" },
	{ code: "DEN", fullName: "Denver Broncos", shortName: "Denver" },
	{ code: "DET", fullName: "Detroit Lions", shortName: "Detroit" },
	{ code: "GB", fullName: "Green Bay Packers", shortName: "Green Bay" },
	{ code: "HOU", fullName: "Houston Texans", shortName: "Houston" },
	{ code: "IND", fullName: "Indianapolis Colts", shortName: "Indianapolis" },
	{ code: "JAC", fullName: "Jacksonville Jaguars", shortName: "Jacksonville" },
	{ code: "KC", fullName: "Kansas City Chiefs", shortName: "Kansas City" },
	{ code: "MIA", fullName: "Miami Dolphins", shortName: "Miami" },
	{ code: "MIN", fullName: "Minnesota Vikings", shortName: "Minnesota" },
	{ code: "NE", fullName: "New England Patriots", shortName: "New England" },
	{ code: "NO", fullName: "New Orleans Saints", shortName: "New Orleans" },
	{ code: "NYG", fullName: "New York Giants", shortName: "N.Y. Giants" },
	{ code: "NYJ", fullName: "New York Jets", shortName: "N.Y. Jets" },
	{ code: "LV", fullName: "Las Vegas Raiders", shortName: "Las Vegas" },
	{ code: "PHI", fullName: "Philadelphia Eagles", shortName: "Philadelphia" },
	{ code: "PIT", fullName: "Pittsburgh Steelers", shortName: "Pittsburgh" },
	{ code: "LAC", fullName: "Los Angeles Chargers", shortName: "L.A. Chargers" },
	{ code: "SEA", fullName: "Seattle Seahawks", shortName: "Seattle" },
	{ code: "SF", fullName: "San Francisco 49ers", shortName: "San Francisco" },
	{ code: "LAR", fullName: "Los Angeles Rams", shortName: "L.A. Rams" },
	{ code: "TB", fullName: "Tampa Bay Buccaneers", shortName: "Tampa Bay" },
	{ code: "TEN", fullName: "Tennessee Titans", shortName: "Tennessee" },
	{ code: "WAS", fullName: "Washington Redskins", shortName: "Washington" },
];

const schedule = [
	{
		gameId: "1",
		gameWeek: "1",
		gameDate: "2020-09-10",
		awayTeam: "HOU",
		homeTeam: "KC",
		gameTimeET: "8:20 PM",
		tvStation: "NBC",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "2",
		gameWeek: "1",
		gameDate: "2020-09-13",
		awayTeam: "SEA",
		homeTeam: "ATL",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "3",
		gameWeek: "1",
		gameDate: "2020-09-13",
		awayTeam: "NYJ",
		homeTeam: "BUF",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "4",
		gameWeek: "1",
		gameDate: "2020-09-13",
		awayTeam: "CHI",
		homeTeam: "DET",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "5",
		gameWeek: "1",
		gameDate: "2020-09-13",
		awayTeam: "GB",
		homeTeam: "MIN",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "6",
		gameWeek: "1",
		gameDate: "2020-09-13",
		awayTeam: "MIA",
		homeTeam: "NE",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "7",
		gameWeek: "1",
		gameDate: "2020-09-13",
		awayTeam: "PHI",
		homeTeam: "WAS",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "8",
		gameWeek: "1",
		gameDate: "2020-09-13",
		awayTeam: "LV",
		homeTeam: "CAR",
		gameTimeET: "1:00 PM",
		tvStation: "",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "9",
		gameWeek: "1",
		gameDate: "2020-09-13",
		awayTeam: "IND",
		homeTeam: "JAC",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "10",
		gameWeek: "1",
		gameDate: "2020-09-13",
		awayTeam: "CLE",
		homeTeam: "BAL",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "11",
		gameWeek: "1",
		gameDate: "2020-09-13",
		awayTeam: "LAC",
		homeTeam: "CIN",
		gameTimeET: "4:05 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "12",
		gameWeek: "1",
		gameDate: "2020-09-13",
		awayTeam: "TB",
		homeTeam: "NO",
		gameTimeET: "4:25 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "13",
		gameWeek: "1",
		gameDate: "2020-09-13",
		awayTeam: "ARI",
		homeTeam: "SF",
		gameTimeET: "4:25 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "14",
		gameWeek: "1",
		gameDate: "2020-09-13",
		awayTeam: "DAL",
		homeTeam: "LAR",
		gameTimeET: "8:20 PM",
		tvStation: "NBC",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "15",
		gameWeek: "1",
		gameDate: "2020-09-14",
		awayTeam: "PIT",
		homeTeam: "NYG",
		gameTimeET: "7:15 PM",
		tvStation: "ESPN",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "16",
		gameWeek: "1",
		gameDate: "2020-09-14",
		awayTeam: "TEN",
		homeTeam: "DEN",
		gameTimeET: "10:10 PM",
		tvStation: "ESPN",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "17",
		gameWeek: "2",
		gameDate: "2020-09-17",
		awayTeam: "CIN",
		homeTeam: "CLE",
		gameTimeET: "8:20 PM",
		tvStation: "NFL",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "18",
		gameWeek: "2",
		gameDate: "2020-09-20",
		awayTeam: "NYG",
		homeTeam: "CHI",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "19",
		gameWeek: "2",
		gameDate: "2020-09-20",
		awayTeam: "ATL",
		homeTeam: "DAL",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "20",
		gameWeek: "2",
		gameDate: "2020-09-20",
		awayTeam: "DET",
		homeTeam: "GB",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "21",
		gameWeek: "2",
		gameDate: "2020-09-20",
		awayTeam: "JAC",
		homeTeam: "TEN",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "22",
		gameWeek: "2",
		gameDate: "2020-09-20",
		awayTeam: "MIN",
		homeTeam: "IND",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "23",
		gameWeek: "2",
		gameDate: "2020-09-20",
		awayTeam: "BUF",
		homeTeam: "MIA",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "24",
		gameWeek: "2",
		gameDate: "2020-09-20",
		awayTeam: "SF",
		homeTeam: "NYJ",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "25",
		gameWeek: "2",
		gameDate: "2020-09-20",
		awayTeam: "LAR",
		homeTeam: "PHI",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "26",
		gameWeek: "2",
		gameDate: "2020-09-20",
		awayTeam: "DEN",
		homeTeam: "PIT",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "27",
		gameWeek: "2",
		gameDate: "2020-09-20",
		awayTeam: "CAR",
		homeTeam: "TB",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "28",
		gameWeek: "2",
		gameDate: "2020-09-20",
		awayTeam: "WAS",
		homeTeam: "ARI",
		gameTimeET: "4:05 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "29",
		gameWeek: "2",
		gameDate: "2020-09-20",
		awayTeam: "KC",
		homeTeam: "LAC",
		gameTimeET: "4:25 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "30",
		gameWeek: "2",
		gameDate: "2020-09-20",
		awayTeam: "BAL",
		homeTeam: "HOU",
		gameTimeET: "4:25 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "31",
		gameWeek: "2",
		gameDate: "2020-09-20",
		awayTeam: "NE",
		homeTeam: "SEA",
		gameTimeET: "8:20 PM",
		tvStation: "NBC",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "32",
		gameWeek: "2",
		gameDate: "2020-09-21",
		awayTeam: "NO",
		homeTeam: "LV",
		gameTimeET: "8:15 PM",
		tvStation: "ESPN",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "33",
		gameWeek: "3",
		gameDate: "2020-09-24",
		awayTeam: "MIA",
		homeTeam: "JAC",
		gameTimeET: "8:20 PM",
		tvStation: "NFL",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "34",
		gameWeek: "3",
		gameDate: "2020-09-27",
		awayTeam: "CHI",
		homeTeam: "ATL",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "35",
		gameWeek: "3",
		gameDate: "2020-09-27",
		awayTeam: "LAR",
		homeTeam: "BUF",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "36",
		gameWeek: "3",
		gameDate: "2020-09-27",
		awayTeam: "WAS",
		homeTeam: "CLE",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "37",
		gameWeek: "3",
		gameDate: "2020-09-27",
		awayTeam: "TEN",
		homeTeam: "MIN",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "38",
		gameWeek: "3",
		gameDate: "2020-09-27",
		awayTeam: "LV",
		homeTeam: "NE",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "39",
		gameWeek: "3",
		gameDate: "2020-09-27",
		awayTeam: "SF",
		homeTeam: "NYG",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "40",
		gameWeek: "3",
		gameDate: "2020-09-27",
		awayTeam: "CIN",
		homeTeam: "PHI",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "41",
		gameWeek: "3",
		gameDate: "2020-09-27",
		awayTeam: "HOU",
		homeTeam: "PIT",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "42",
		gameWeek: "3",
		gameDate: "2020-09-27",
		awayTeam: "NYJ",
		homeTeam: "IND",
		gameTimeET: "4:05 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "43",
		gameWeek: "3",
		gameDate: "2020-09-27",
		awayTeam: "CAR",
		homeTeam: "LAC",
		gameTimeET: "4:05 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "44",
		gameWeek: "3",
		gameDate: "2020-09-27",
		awayTeam: "TB",
		homeTeam: "DEN",
		gameTimeET: "4:25 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "45",
		gameWeek: "3",
		gameDate: "2020-09-27",
		awayTeam: "DET",
		homeTeam: "ARI",
		gameTimeET: "4:25 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "46",
		gameWeek: "3",
		gameDate: "2020-09-27",
		awayTeam: "DAL",
		homeTeam: "SEA",
		gameTimeET: "4:25 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "47",
		gameWeek: "3",
		gameDate: "2020-09-27",
		awayTeam: "GB",
		homeTeam: "NO",
		gameTimeET: "8:20 PM",
		tvStation: "NBC",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "48",
		gameWeek: "3",
		gameDate: "2020-09-28",
		awayTeam: "KC",
		homeTeam: "BAL",
		gameTimeET: "8:15 PM",
		tvStation: "ESPN",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "49",
		gameWeek: "4",
		gameDate: "2020-10-01",
		awayTeam: "DEN",
		homeTeam: "NYJ",
		gameTimeET: "8:20 PM",
		tvStation: "NFL",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "50",
		gameWeek: "4",
		gameDate: "2020-10-04",
		awayTeam: "IND",
		homeTeam: "CHI",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "51",
		gameWeek: "4",
		gameDate: "2020-10-04",
		awayTeam: "JAC",
		homeTeam: "CIN",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "52",
		gameWeek: "4",
		gameDate: "2020-10-04",
		awayTeam: "CLE",
		homeTeam: "DAL",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "53",
		gameWeek: "4",
		gameDate: "2020-10-04",
		awayTeam: "NO",
		homeTeam: "DET",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "54",
		gameWeek: "4",
		gameDate: "2020-10-04",
		awayTeam: "PIT",
		homeTeam: "TEN",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "55",
		gameWeek: "4",
		gameDate: "2020-10-04",
		awayTeam: "SEA",
		homeTeam: "MIA",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "56",
		gameWeek: "4",
		gameDate: "2020-10-04",
		awayTeam: "LAC",
		homeTeam: "TB",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "57",
		gameWeek: "4",
		gameDate: "2020-10-04",
		awayTeam: "BAL",
		homeTeam: "WAS",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "58",
		gameWeek: "4",
		gameDate: "2020-10-04",
		awayTeam: "ARI",
		homeTeam: "CAR",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "59",
		gameWeek: "4",
		gameDate: "2020-10-04",
		awayTeam: "MIN",
		homeTeam: "HOU",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "60",
		gameWeek: "4",
		gameDate: "2020-10-04",
		awayTeam: "NYG",
		homeTeam: "LAR",
		gameTimeET: "4:05 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "61",
		gameWeek: "4",
		gameDate: "2020-10-04",
		awayTeam: "NE",
		homeTeam: "KC",
		gameTimeET: "4:25 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "62",
		gameWeek: "4",
		gameDate: "2020-10-04",
		awayTeam: "BUF",
		homeTeam: "LV",
		gameTimeET: "4:25 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "63",
		gameWeek: "4",
		gameDate: "2020-10-04",
		awayTeam: "PHI",
		homeTeam: "SF",
		gameTimeET: "8:20 PM",
		tvStation: "NBC",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "64",
		gameWeek: "4",
		gameDate: "2020-10-05",
		awayTeam: "ATL",
		homeTeam: "GB",
		gameTimeET: "8:15 PM",
		tvStation: "ESPN",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "65",
		gameWeek: "5",
		gameDate: "2020-10-08",
		awayTeam: "TB",
		homeTeam: "CHI",
		gameTimeET: "8:20 PM",
		tvStation: "FOX/NFL",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "66",
		gameWeek: "5",
		gameDate: "2020-10-11",
		awayTeam: "CAR",
		homeTeam: "ATL",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "67",
		gameWeek: "5",
		gameDate: "2020-10-11",
		awayTeam: "BUF",
		homeTeam: "TEN",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "68",
		gameWeek: "5",
		gameDate: "2020-10-11",
		awayTeam: "LV",
		homeTeam: "KC",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "69",
		gameWeek: "5",
		gameDate: "2020-10-11",
		awayTeam: "DEN",
		homeTeam: "NE",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "70",
		gameWeek: "5",
		gameDate: "2020-10-11",
		awayTeam: "ARI",
		homeTeam: "NYJ",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "71",
		gameWeek: "5",
		gameDate: "2020-10-11",
		awayTeam: "PHI",
		homeTeam: "PIT",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "72",
		gameWeek: "5",
		gameDate: "2020-10-11",
		awayTeam: "LAR",
		homeTeam: "WAS",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "73",
		gameWeek: "5",
		gameDate: "2020-10-11",
		awayTeam: "CIN",
		homeTeam: "BAL",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "74",
		gameWeek: "5",
		gameDate: "2020-10-11",
		awayTeam: "JAC",
		homeTeam: "HOU",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "75",
		gameWeek: "5",
		gameDate: "2020-10-11",
		awayTeam: "MIA",
		homeTeam: "SF",
		gameTimeET: "4:05 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "76",
		gameWeek: "5",
		gameDate: "2020-10-11",
		awayTeam: "IND",
		homeTeam: "CLE",
		gameTimeET: "4:25 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "77",
		gameWeek: "5",
		gameDate: "2020-10-11",
		awayTeam: "NYG",
		homeTeam: "DAL",
		gameTimeET: "4:25 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "78",
		gameWeek: "5",
		gameDate: "2020-10-11",
		awayTeam: "MIN",
		homeTeam: "SEA",
		gameTimeET: "8:20 PM",
		tvStation: "NBC",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "79",
		gameWeek: "5",
		gameDate: "2020-10-12",
		awayTeam: "LAC",
		homeTeam: "NO",
		gameTimeET: "8:15 PM",
		tvStation: "ESPN",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "80",
		gameWeek: "6",
		gameDate: "2020-10-15",
		awayTeam: "KC",
		homeTeam: "BUF",
		gameTimeET: "8:20 PM",
		tvStation: "FOX/NFL",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "81",
		gameWeek: "6",
		gameDate: "2020-10-18",
		awayTeam: "HOU",
		homeTeam: "TEN",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "82",
		gameWeek: "6",
		gameDate: "2020-10-18",
		awayTeam: "CIN",
		homeTeam: "IND",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "83",
		gameWeek: "6",
		gameDate: "2020-10-18",
		awayTeam: "ATL",
		homeTeam: "MIN",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "84",
		gameWeek: "6",
		gameDate: "2020-10-18",
		awayTeam: "WAS",
		homeTeam: "NYG",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "85",
		gameWeek: "6",
		gameDate: "2020-10-18",
		awayTeam: "BAL",
		homeTeam: "PHI",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "86",
		gameWeek: "6",
		gameDate: "2020-10-18",
		awayTeam: "CLE",
		homeTeam: "PIT",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "87",
		gameWeek: "6",
		gameDate: "2020-10-18",
		awayTeam: "CHI",
		homeTeam: "CAR",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "88",
		gameWeek: "6",
		gameDate: "2020-10-18",
		awayTeam: "DET",
		homeTeam: "JAC",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "89",
		gameWeek: "6",
		gameDate: "2020-10-18",
		awayTeam: "MIA",
		homeTeam: "DEN",
		gameTimeET: "4:05 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "90",
		gameWeek: "6",
		gameDate: "2020-10-18",
		awayTeam: "NYJ",
		homeTeam: "LAC",
		gameTimeET: "4:05 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "91",
		gameWeek: "6",
		gameDate: "2020-10-18",
		awayTeam: "GB",
		homeTeam: "TB",
		gameTimeET: "4:25 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "92",
		gameWeek: "6",
		gameDate: "2020-10-18",
		awayTeam: "LAR",
		homeTeam: "SF",
		gameTimeET: "8:20 PM",
		tvStation: "NBC",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "93",
		gameWeek: "6",
		gameDate: "2020-10-19",
		awayTeam: "ARI",
		homeTeam: "DAL",
		gameTimeET: "8:15 PM",
		tvStation: "ESPN",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "94",
		gameWeek: "7",
		gameDate: "2020-10-22",
		awayTeam: "NYG",
		homeTeam: "PHI",
		gameTimeET: "8:20 PM",
		tvStation: "FOX/NFL",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "95",
		gameWeek: "7",
		gameDate: "2020-10-25",
		awayTeam: "DET",
		homeTeam: "ATL",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "96",
		gameWeek: "7",
		gameDate: "2020-10-25",
		awayTeam: "CLE",
		homeTeam: "CIN",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "97",
		gameWeek: "7",
		gameDate: "2020-10-25",
		awayTeam: "LAC",
		homeTeam: "MIA",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "98",
		gameWeek: "7",
		gameDate: "2020-10-25",
		awayTeam: "CAR",
		homeTeam: "NO",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "99",
		gameWeek: "7",
		gameDate: "2020-10-25",
		awayTeam: "BUF",
		homeTeam: "NYJ",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "100",
		gameWeek: "7",
		gameDate: "2020-10-25",
		awayTeam: "DAL",
		homeTeam: "WAS",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "101",
		gameWeek: "7",
		gameDate: "2020-10-25",
		awayTeam: "PIT",
		homeTeam: "BAL",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "102",
		gameWeek: "7",
		gameDate: "2020-10-25",
		awayTeam: "GB",
		homeTeam: "HOU",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "103",
		gameWeek: "7",
		gameDate: "2020-10-25",
		awayTeam: "SEA",
		homeTeam: "ARI",
		gameTimeET: "4:05 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "104",
		gameWeek: "7",
		gameDate: "2020-10-25",
		awayTeam: "KC",
		homeTeam: "DEN",
		gameTimeET: "4:25 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "105",
		gameWeek: "7",
		gameDate: "2020-10-25",
		awayTeam: "SF",
		homeTeam: "NE",
		gameTimeET: "4:25 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "106",
		gameWeek: "7",
		gameDate: "2020-10-25",
		awayTeam: "TB",
		homeTeam: "LV",
		gameTimeET: "8:20 PM",
		tvStation: "NBC",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "107",
		gameWeek: "7",
		gameDate: "2020-10-26",
		awayTeam: "CHI",
		homeTeam: "LAR",
		gameTimeET: "8:15 PM",
		tvStation: "ESPN",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "108",
		gameWeek: "8",
		gameDate: "2020-10-29",
		awayTeam: "ATL",
		homeTeam: "CAR",
		gameTimeET: "8:20 PM",
		tvStation: "FOX/NFL",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "109",
		gameWeek: "8",
		gameDate: "2020-11-01",
		awayTeam: "NE",
		homeTeam: "BUF",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "110",
		gameWeek: "8",
		gameDate: "2020-11-01",
		awayTeam: "TEN",
		homeTeam: "CIN",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "111",
		gameWeek: "8",
		gameDate: "2020-11-01",
		awayTeam: "LV",
		homeTeam: "CLE",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "112",
		gameWeek: "8",
		gameDate: "2020-11-01",
		awayTeam: "IND",
		homeTeam: "DET",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "113",
		gameWeek: "8",
		gameDate: "2020-11-01",
		awayTeam: "MIN",
		homeTeam: "GB",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "114",
		gameWeek: "8",
		gameDate: "2020-11-01",
		awayTeam: "NYJ",
		homeTeam: "KC",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "115",
		gameWeek: "8",
		gameDate: "2020-11-01",
		awayTeam: "LAR",
		homeTeam: "MIA",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "116",
		gameWeek: "8",
		gameDate: "2020-11-01",
		awayTeam: "JAC",
		homeTeam: "LAC",
		gameTimeET: "4:05 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "117",
		gameWeek: "8",
		gameDate: "2020-11-01",
		awayTeam: "NO",
		homeTeam: "CHI",
		gameTimeET: "4:25 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "118",
		gameWeek: "8",
		gameDate: "2020-11-01",
		awayTeam: "SF",
		homeTeam: "SEA",
		gameTimeET: "4:25 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "119",
		gameWeek: "8",
		gameDate: "2020-11-01",
		awayTeam: "DAL",
		homeTeam: "PHI",
		gameTimeET: "8:20 PM",
		tvStation: "NBC",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "120",
		gameWeek: "8",
		gameDate: "2020-11-02",
		awayTeam: "TB",
		homeTeam: "NYG",
		gameTimeET: "8:15 PM",
		tvStation: "ESPN",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "121",
		gameWeek: "9",
		gameDate: "2020-11-05",
		awayTeam: "GB",
		homeTeam: "SF",
		gameTimeET: "8:20 PM",
		tvStation: "FOX/NFL",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "122",
		gameWeek: "9",
		gameDate: "2020-11-08",
		awayTeam: "DEN",
		homeTeam: "ATL",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "123",
		gameWeek: "9",
		gameDate: "2020-11-08",
		awayTeam: "SEA",
		homeTeam: "BUF",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "124",
		gameWeek: "9",
		gameDate: "2020-11-08",
		awayTeam: "CHI",
		homeTeam: "TEN",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "125",
		gameWeek: "9",
		gameDate: "2020-11-08",
		awayTeam: "BAL",
		homeTeam: "IND",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "126",
		gameWeek: "9",
		gameDate: "2020-11-08",
		awayTeam: "CAR",
		homeTeam: "KC",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "127",
		gameWeek: "9",
		gameDate: "2020-11-08",
		awayTeam: "DET",
		homeTeam: "MIN",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "128",
		gameWeek: "9",
		gameDate: "2020-11-08",
		awayTeam: "NYG",
		homeTeam: "WAS",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "129",
		gameWeek: "9",
		gameDate: "2020-11-08",
		awayTeam: "HOU",
		homeTeam: "JAC",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "130",
		gameWeek: "9",
		gameDate: "2020-11-08",
		awayTeam: "LV",
		homeTeam: "LAC",
		gameTimeET: "4:05 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "131",
		gameWeek: "9",
		gameDate: "2020-11-08",
		awayTeam: "PIT",
		homeTeam: "DAL",
		gameTimeET: "4:25 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "132",
		gameWeek: "9",
		gameDate: "2020-11-08",
		awayTeam: "MIA",
		homeTeam: "ARI",
		gameTimeET: "4:25 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "133",
		gameWeek: "9",
		gameDate: "2020-11-08",
		awayTeam: "NO",
		homeTeam: "TB",
		gameTimeET: "8:20 PM",
		tvStation: "NBC",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "134",
		gameWeek: "9",
		gameDate: "2020-11-09",
		awayTeam: "NE",
		homeTeam: "NYJ",
		gameTimeET: "8:15 PM",
		tvStation: "ESPN",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "135",
		gameWeek: "10",
		gameDate: "2020-11-12",
		awayTeam: "IND",
		homeTeam: "TEN",
		gameTimeET: "8:20 PM",
		tvStation: "FOX/NFL",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "136",
		gameWeek: "10",
		gameDate: "2020-11-15",
		awayTeam: "HOU",
		homeTeam: "CLE",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "137",
		gameWeek: "10",
		gameDate: "2020-11-15",
		awayTeam: "WAS",
		homeTeam: "DET",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "138",
		gameWeek: "10",
		gameDate: "2020-11-15",
		awayTeam: "JAC",
		homeTeam: "GB",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "139",
		gameWeek: "10",
		gameDate: "2020-11-15",
		awayTeam: "PHI",
		homeTeam: "NYG",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "140",
		gameWeek: "10",
		gameDate: "2020-11-15",
		awayTeam: "CIN",
		homeTeam: "PIT",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "141",
		gameWeek: "10",
		gameDate: "2020-11-15",
		awayTeam: "TB",
		homeTeam: "CAR",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "142",
		gameWeek: "10",
		gameDate: "2020-11-15",
		awayTeam: "DEN",
		homeTeam: "LV",
		gameTimeET: "4:05 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "143",
		gameWeek: "10",
		gameDate: "2020-11-15",
		awayTeam: "NYJ",
		homeTeam: "MIA",
		gameTimeET: "4:05 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "144",
		gameWeek: "10",
		gameDate: "2020-11-15",
		awayTeam: "BUF",
		homeTeam: "ARI",
		gameTimeET: "4:05 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "145",
		gameWeek: "10",
		gameDate: "2020-11-15",
		awayTeam: "SEA",
		homeTeam: "LAR",
		gameTimeET: "4:25 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "146",
		gameWeek: "10",
		gameDate: "2020-11-15",
		awayTeam: "SF",
		homeTeam: "NO",
		gameTimeET: "4:25 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "147",
		gameWeek: "10",
		gameDate: "2020-11-15",
		awayTeam: "BAL",
		homeTeam: "NE",
		gameTimeET: "8:20 PM",
		tvStation: "NBC",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "148",
		gameWeek: "10",
		gameDate: "2020-11-16",
		awayTeam: "MIN",
		homeTeam: "CHI",
		gameTimeET: "8:15 PM",
		tvStation: "ESPN",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "149",
		gameWeek: "11",
		gameDate: "2020-11-19",
		awayTeam: "ARI",
		homeTeam: "SEA",
		gameTimeET: "8:20 PM",
		tvStation: "FOX/NFL",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "150",
		gameWeek: "11",
		gameDate: "2020-11-22",
		awayTeam: "PHI",
		homeTeam: "CLE",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "151",
		gameWeek: "11",
		gameDate: "2020-11-22",
		awayTeam: "GB",
		homeTeam: "IND",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "152",
		gameWeek: "11",
		gameDate: "2020-11-22",
		awayTeam: "ATL",
		homeTeam: "NO",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "153",
		gameWeek: "11",
		gameDate: "2020-11-22",
		awayTeam: "CIN",
		homeTeam: "WAS",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "154",
		gameWeek: "11",
		gameDate: "2020-11-22",
		awayTeam: "DET",
		homeTeam: "CAR",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "155",
		gameWeek: "11",
		gameDate: "2020-11-22",
		awayTeam: "PIT",
		homeTeam: "JAC",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "156",
		gameWeek: "11",
		gameDate: "2020-11-22",
		awayTeam: "TEN",
		homeTeam: "BAL",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "157",
		gameWeek: "11",
		gameDate: "2020-11-22",
		awayTeam: "NE",
		homeTeam: "HOU",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "158",
		gameWeek: "11",
		gameDate: "2020-11-22",
		awayTeam: "LAC",
		homeTeam: "DEN",
		gameTimeET: "4:05 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "159",
		gameWeek: "11",
		gameDate: "2020-11-22",
		awayTeam: "DAL",
		homeTeam: "MIN",
		gameTimeET: "4:25 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "160",
		gameWeek: "11",
		gameDate: "2020-11-22",
		awayTeam: "KC",
		homeTeam: "LV",
		gameTimeET: "8:20 PM",
		tvStation: "NBC",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "161",
		gameWeek: "11",
		gameDate: "2020-11-23",
		awayTeam: "LAR",
		homeTeam: "TB",
		gameTimeET: "8:15 PM",
		tvStation: "ESPN",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "162",
		gameWeek: "12",
		gameDate: "2020-11-26",
		awayTeam: "HOU",
		homeTeam: "DET",
		gameTimeET: "12:30 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "163",
		gameWeek: "12",
		gameDate: "2020-11-26",
		awayTeam: "WAS",
		homeTeam: "DAL",
		gameTimeET: "4:30 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "164",
		gameWeek: "12",
		gameDate: "2020-11-26",
		awayTeam: "BAL",
		homeTeam: "PIT",
		gameTimeET: "8:20 PM",
		tvStation: "NBC",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "165",
		gameWeek: "12",
		gameDate: "2020-11-29",
		awayTeam: "LV",
		homeTeam: "ATL",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "166",
		gameWeek: "12",
		gameDate: "2020-11-29",
		awayTeam: "LAC",
		homeTeam: "BUF",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "167",
		gameWeek: "12",
		gameDate: "2020-11-29",
		awayTeam: "NYG",
		homeTeam: "CIN",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "168",
		gameWeek: "12",
		gameDate: "2020-11-29",
		awayTeam: "TEN",
		homeTeam: "IND",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "169",
		gameWeek: "12",
		gameDate: "2020-11-29",
		awayTeam: "CAR",
		homeTeam: "MIN",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "170",
		gameWeek: "12",
		gameDate: "2020-11-29",
		awayTeam: "ARI",
		homeTeam: "NE",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "171",
		gameWeek: "12",
		gameDate: "2020-11-29",
		awayTeam: "MIA",
		homeTeam: "NYJ",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "172",
		gameWeek: "12",
		gameDate: "2020-11-29",
		awayTeam: "CLE",
		homeTeam: "JAC",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "173",
		gameWeek: "12",
		gameDate: "2020-11-29",
		awayTeam: "NO",
		homeTeam: "DEN",
		gameTimeET: "4:05 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "174",
		gameWeek: "12",
		gameDate: "2020-11-29",
		awayTeam: "SF",
		homeTeam: "LAR",
		gameTimeET: "4:05 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "175",
		gameWeek: "12",
		gameDate: "2020-11-29",
		awayTeam: "KC",
		homeTeam: "TB",
		gameTimeET: "4:25 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "176",
		gameWeek: "12",
		gameDate: "2020-11-29",
		awayTeam: "CHI",
		homeTeam: "GB",
		gameTimeET: "8:20 PM",
		tvStation: "NBC",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "177",
		gameWeek: "12",
		gameDate: "2020-11-30",
		awayTeam: "SEA",
		homeTeam: "PHI",
		gameTimeET: "8:15 PM",
		tvStation: "ESPN",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "178",
		gameWeek: "13",
		gameDate: "2020-12-03",
		awayTeam: "DAL",
		homeTeam: "BAL",
		gameTimeET: "8:20 PM",
		tvStation: "FOX/NFL",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "179",
		gameWeek: "13",
		gameDate: "2020-12-06",
		awayTeam: "NO",
		homeTeam: "ATL",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "180",
		gameWeek: "13",
		gameDate: "2020-12-06",
		awayTeam: "DET",
		homeTeam: "CHI",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "181",
		gameWeek: "13",
		gameDate: "2020-12-06",
		awayTeam: "CLE",
		homeTeam: "TEN",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "182",
		gameWeek: "13",
		gameDate: "2020-12-06",
		awayTeam: "CIN",
		homeTeam: "MIA",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "183",
		gameWeek: "13",
		gameDate: "2020-12-06",
		awayTeam: "JAC",
		homeTeam: "MIN",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "184",
		gameWeek: "13",
		gameDate: "2020-12-06",
		awayTeam: "LV",
		homeTeam: "NYJ",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "185",
		gameWeek: "13",
		gameDate: "2020-12-06",
		awayTeam: "WAS",
		homeTeam: "PIT",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "186",
		gameWeek: "13",
		gameDate: "2020-12-06",
		awayTeam: "IND",
		homeTeam: "HOU",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "187",
		gameWeek: "13",
		gameDate: "2020-12-06",
		awayTeam: "LAR",
		homeTeam: "ARI",
		gameTimeET: "4:05 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "188",
		gameWeek: "13",
		gameDate: "2020-12-06",
		awayTeam: "NYG",
		homeTeam: "SEA",
		gameTimeET: "4:05 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "189",
		gameWeek: "13",
		gameDate: "2020-12-06",
		awayTeam: "PHI",
		homeTeam: "GB",
		gameTimeET: "4:25 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "190",
		gameWeek: "13",
		gameDate: "2020-12-06",
		awayTeam: "NE",
		homeTeam: "LAC",
		gameTimeET: "4:25 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "191",
		gameWeek: "13",
		gameDate: "2020-12-06",
		awayTeam: "DEN",
		homeTeam: "KC",
		gameTimeET: "8:20 PM",
		tvStation: "NBC",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "192",
		gameWeek: "13",
		gameDate: "2020-12-07",
		awayTeam: "BUF",
		homeTeam: "SF",
		gameTimeET: "8:15 PM",
		tvStation: "ESPN",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "193",
		gameWeek: "14",
		gameDate: "2020-12-10",
		awayTeam: "NE",
		homeTeam: "LAR",
		gameTimeET: "8:20 PM",
		tvStation: "FOX/NFL",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "194",
		gameWeek: "14",
		gameDate: "2020-12-13",
		awayTeam: "HOU",
		homeTeam: "CHI",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "195",
		gameWeek: "14",
		gameDate: "2020-12-13",
		awayTeam: "DAL",
		homeTeam: "CIN",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "196",
		gameWeek: "14",
		gameDate: "2020-12-13",
		awayTeam: "GB",
		homeTeam: "DET",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "197",
		gameWeek: "14",
		gameDate: "2020-12-13",
		awayTeam: "KC",
		homeTeam: "MIA",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "198",
		gameWeek: "14",
		gameDate: "2020-12-13",
		awayTeam: "ARI",
		homeTeam: "NYG",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "199",
		gameWeek: "14",
		gameDate: "2020-12-13",
		awayTeam: "MIN",
		homeTeam: "TB",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "200",
		gameWeek: "14",
		gameDate: "2020-12-13",
		awayTeam: "DEN",
		homeTeam: "CAR",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "201",
		gameWeek: "14",
		gameDate: "2020-12-13",
		awayTeam: "TEN",
		homeTeam: "JAC",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "202",
		gameWeek: "14",
		gameDate: "2020-12-13",
		awayTeam: "IND",
		homeTeam: "LV",
		gameTimeET: "4:05 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "203",
		gameWeek: "14",
		gameDate: "2020-12-13",
		awayTeam: "NYJ",
		homeTeam: "SEA",
		gameTimeET: "4:05 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "204",
		gameWeek: "14",
		gameDate: "2020-12-13",
		awayTeam: "NO",
		homeTeam: "PHI",
		gameTimeET: "4:25 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "205",
		gameWeek: "14",
		gameDate: "2020-12-13",
		awayTeam: "ATL",
		homeTeam: "LAC",
		gameTimeET: "4:25 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "206",
		gameWeek: "14",
		gameDate: "2020-12-13",
		awayTeam: "WAS",
		homeTeam: "SF",
		gameTimeET: "4:25 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "207",
		gameWeek: "14",
		gameDate: "2020-12-13",
		awayTeam: "PIT",
		homeTeam: "BUF",
		gameTimeET: "8:20 PM",
		tvStation: "NBC",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "208",
		gameWeek: "14",
		gameDate: "2020-12-14",
		awayTeam: "BAL",
		homeTeam: "CLE",
		gameTimeET: "8:15 PM",
		tvStation: "ESPN",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "209",
		gameWeek: "15",
		gameDate: "2020-12-17",
		awayTeam: "LAC",
		homeTeam: "LV",
		gameTimeET: "8:20 PM",
		tvStation: "FOX/NFL",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "210",
		gameWeek: "15",
		gameDate: "2020-12-20",
		awayTeam: "BUF",
		homeTeam: "DEN",
		gameTimeET: "7:00 PM",
		tvStation: "",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "211",
		gameWeek: "15",
		gameDate: "2020-12-20",
		awayTeam: "CAR",
		homeTeam: "GB",
		gameTimeET: "7:00 PM",
		tvStation: "",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "212",
		gameWeek: "15",
		gameDate: "2020-12-20",
		awayTeam: "DET",
		homeTeam: "TEN",
		gameTimeET: "7:00 PM",
		tvStation: "",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "213",
		gameWeek: "15",
		gameDate: "2020-12-20",
		awayTeam: "HOU",
		homeTeam: "IND",
		gameTimeET: "7:00 PM",
		tvStation: "",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "214",
		gameWeek: "15",
		gameDate: "2020-12-20",
		awayTeam: "NYJ",
		homeTeam: "LAR",
		gameTimeET: "7:00 PM",
		tvStation: "",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "215",
		gameWeek: "15",
		gameDate: "2020-12-20",
		awayTeam: "TB",
		homeTeam: "ATL",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "216",
		gameWeek: "15",
		gameDate: "2020-12-20",
		awayTeam: "NE",
		homeTeam: "MIA",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "217",
		gameWeek: "15",
		gameDate: "2020-12-20",
		awayTeam: "CHI",
		homeTeam: "MIN",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "218",
		gameWeek: "15",
		gameDate: "2020-12-20",
		awayTeam: "CLE",
		homeTeam: "NYG",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "219",
		gameWeek: "15",
		gameDate: "2020-12-20",
		awayTeam: "SEA",
		homeTeam: "WAS",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "220",
		gameWeek: "15",
		gameDate: "2020-12-20",
		awayTeam: "JAC",
		homeTeam: "BAL",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "221",
		gameWeek: "15",
		gameDate: "2020-12-20",
		awayTeam: "PHI",
		homeTeam: "ARI",
		gameTimeET: "4:05 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "222",
		gameWeek: "15",
		gameDate: "2020-12-20",
		awayTeam: "KC",
		homeTeam: "NO",
		gameTimeET: "4:25 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "223",
		gameWeek: "15",
		gameDate: "2020-12-20",
		awayTeam: "SF",
		homeTeam: "DAL",
		gameTimeET: "8:20 PM",
		tvStation: "NBC",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "224",
		gameWeek: "15",
		gameDate: "2020-12-21",
		awayTeam: "PIT",
		homeTeam: "CIN",
		gameTimeET: "8:15 PM",
		tvStation: "ESPN",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "225",
		gameWeek: "16",
		gameDate: "2020-12-25",
		awayTeam: "MIN",
		homeTeam: "NO",
		gameTimeET: "4:30 PM",
		tvStation: "FOX/NFL",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "226",
		gameWeek: "16",
		gameDate: "2020-12-27",
		awayTeam: "TB",
		homeTeam: "DET",
		gameTimeET: "7:00 PM",
		tvStation: "",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "227",
		gameWeek: "16",
		gameDate: "2020-12-27",
		awayTeam: "MIA",
		homeTeam: "LV",
		gameTimeET: "7:00 PM",
		tvStation: "",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "228",
		gameWeek: "16",
		gameDate: "2020-12-27",
		awayTeam: "CLE",
		homeTeam: "NYJ",
		gameTimeET: "7:00 PM",
		tvStation: "",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "229",
		gameWeek: "16",
		gameDate: "2020-12-27",
		awayTeam: "SF",
		homeTeam: "ARI",
		gameTimeET: "7:00 PM",
		tvStation: "",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "230",
		gameWeek: "16",
		gameDate: "2020-12-27",
		awayTeam: "DEN",
		homeTeam: "LAC",
		gameTimeET: "7:00 PM",
		tvStation: "",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "231",
		gameWeek: "16",
		gameDate: "2020-12-27",
		awayTeam: "ATL",
		homeTeam: "KC",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "232",
		gameWeek: "16",
		gameDate: "2020-12-27",
		awayTeam: "IND",
		homeTeam: "PIT",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "233",
		gameWeek: "16",
		gameDate: "2020-12-27",
		awayTeam: "CAR",
		homeTeam: "WAS",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "234",
		gameWeek: "16",
		gameDate: "2020-12-27",
		awayTeam: "CHI",
		homeTeam: "JAC",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "235",
		gameWeek: "16",
		gameDate: "2020-12-27",
		awayTeam: "NYG",
		homeTeam: "BAL",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "236",
		gameWeek: "16",
		gameDate: "2020-12-27",
		awayTeam: "CIN",
		homeTeam: "HOU",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "237",
		gameWeek: "16",
		gameDate: "2020-12-27",
		awayTeam: "LAR",
		homeTeam: "SEA",
		gameTimeET: "4:05 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "238",
		gameWeek: "16",
		gameDate: "2020-12-27",
		awayTeam: "PHI",
		homeTeam: "DAL",
		gameTimeET: "4:25 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "239",
		gameWeek: "16",
		gameDate: "2020-12-27",
		awayTeam: "TEN",
		homeTeam: "GB",
		gameTimeET: "8:20 PM",
		tvStation: "NBC",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "240",
		gameWeek: "16",
		gameDate: "2020-12-28",
		awayTeam: "BUF",
		homeTeam: "NE",
		gameTimeET: "8:15 PM",
		tvStation: "ESPN",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "241",
		gameWeek: "17",
		gameDate: "2021-01-03",
		awayTeam: "MIA",
		homeTeam: "BUF",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "242",
		gameWeek: "17",
		gameDate: "2021-01-03",
		awayTeam: "GB",
		homeTeam: "CHI",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "243",
		gameWeek: "17",
		gameDate: "2021-01-03",
		awayTeam: "BAL",
		homeTeam: "CIN",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "244",
		gameWeek: "17",
		gameDate: "2021-01-03",
		awayTeam: "PIT",
		homeTeam: "CLE",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "245",
		gameWeek: "17",
		gameDate: "2021-01-03",
		awayTeam: "MIN",
		homeTeam: "DET",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "246",
		gameWeek: "17",
		gameDate: "2021-01-03",
		awayTeam: "JAC",
		homeTeam: "IND",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "247",
		gameWeek: "17",
		gameDate: "2021-01-03",
		awayTeam: "LAC",
		homeTeam: "KC",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "248",
		gameWeek: "17",
		gameDate: "2021-01-03",
		awayTeam: "NYJ",
		homeTeam: "NE",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "249",
		gameWeek: "17",
		gameDate: "2021-01-03",
		awayTeam: "DAL",
		homeTeam: "NYG",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "250",
		gameWeek: "17",
		gameDate: "2021-01-03",
		awayTeam: "WAS",
		homeTeam: "PHI",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "251",
		gameWeek: "17",
		gameDate: "2021-01-03",
		awayTeam: "ATL",
		homeTeam: "TB",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "252",
		gameWeek: "17",
		gameDate: "2021-01-03",
		awayTeam: "NO",
		homeTeam: "CAR",
		gameTimeET: "1:00 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "253",
		gameWeek: "17",
		gameDate: "2021-01-03",
		awayTeam: "TEN",
		homeTeam: "HOU",
		gameTimeET: "1:00 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "254",
		gameWeek: "17",
		gameDate: "2021-01-03",
		awayTeam: "LV",
		homeTeam: "DEN",
		gameTimeET: "4:25 PM",
		tvStation: "CBS",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "255",
		gameWeek: "17",
		gameDate: "2021-01-03",
		awayTeam: "ARI",
		homeTeam: "LAR",
		gameTimeET: "4:25 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
	{
		gameId: "256",
		gameWeek: "17",
		gameDate: "2021-01-03",
		awayTeam: "SEA",
		homeTeam: "SF",
		gameTimeET: "4:25 PM",
		tvStation: "FOX",
		winner: "",
		homeScore: "0",
		awayScore: "0",
	},
];

module.exports = {
	teams,
	schedule,
};
